name: Copy Code Snips
run-name: Copy website code snips.
on: [push]
jobs:
  Copy-Snips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: copy
        env:
          SRC_FOLDER_PATH: 'tools/codesnips/snips'
          TARGET_BRANCH: 'codesnips'
        run: |
          python3 tools/codesnips/codesnips.py
          ls tools/codesnips/
          ls tools/codesnips/snips
          git stash save
          #files==$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@gihub.com'
          git fetch
          git checkout $TARGET_BRANCH
          #git checkout ${GITHUB_REF##*/} -- $files
          #cp -r tools/codesnips/snips/* ./
          git stash pop
          cp -r tools/codesnips/snips/* ./
          git diff-index --quiet HEAD || git commit -am "deploy files"
          git push origin $TARGET_BRANCH
