name: Copy Code Snips
run-name: ${{ github.actor }}: Copy website code snips.
on: [push]
jobs:
  Copy-Snips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FOLDER_PATH: 'lc3os'
          TARGET_BRANCH: 'codesnips'
        run: |
          files=/lc3os/lc3o.asm
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@gihub.com'
          git fetch
          git checkout $TARGET_BRANCH
          git checkout ${GITHUB_REF##*/} -- $files
          git add -A
          git diff-index --quiet HEAD || git commit -am "deploy files"
          git push origin $TARGET_BRANCH
